select A.RDB$RELATION_NAME,
A.RDB$CONSTRAINT_NAME,
A.RDB$CONSTRAINT_TYPE,
B.RDB$CONST_NAME_UQ,
B.RDB$UPDATE_RULE,
B.RDB$DELETE_RULE,
C.RDB$RELATION_NAME as FK_Table,
A.RDB$INDEX_NAME,
D.RDB$FIELD_NAME as FK_Field,
E.RDB$FIELD_NAME as OnField,
I.RDB$INDEX_TYPE
from RDB$REF_CONSTRAINTS B, RDB$RELATION_CONSTRAINTS A, RDB$RELATION_CONSTRAINTS C,
RDB$INDEX_SEGMENTS D, RDB$INDEX_SEGMENTS E, RDB$INDICES I
where (A.RDB$CONSTRAINT_TYPE = 'FOREIGN KEY') and
(A.RDB$CONSTRAINT_NAME = B.RDB$CONSTRAINT_NAME) and
(B.RDB$CONST_NAME_UQ=C.RDB$CONSTRAINT_NAME) and (C.RDB$INDEX_NAME=D.RDB$INDEX_NAME) and
(A.RDB$INDEX_NAME=E.RDB$INDEX_NAME) and
(A.RDB$INDEX_NAME=I.RDB$INDEX_NAME)
and (A.RDB$RELATION_NAME = 'tbl_AccountGroupRight')
order by A.RDB$RELATION_NAME, A.RDB$CONSTRAINT_NAME, D.RDB$FIELD_POSITION, E.RDB$FIELD_POSITION